const variables = {
devpoint: "0", 
Money: "0",
prefix: "ak.",
warn: "0",
bank: "0",
Ban: "false",
ban: "0", 
kick: "0",
unmute: "0",
tempmute: "0", 
msg: "0",
mute: "1",
wiki: "0", 
suggestchannel: "",
antilink: "false",
xp: "", 
level: "1",
req: "50",
expcd: "45",
leveling: "disable",
ticketsystem: "off",
ticketdesc: "Problema",
cat: "",
tick: "",
dog: "0",
cat: "0",
mascotas: "0",
subs: "0",
donaciones: "0",
cookies: "0",
sip: "0",
lang: "0",
subsyttw: "0",
seguidores: "0",
pico: "0",
plata: "0",
oro: "0",
diamante: "0",
cobre: "0",
esmeralda: "0",
lapizlazuli: "0",
cuarzo: "0",
caña: "0",
afk: '{"enable":"false","reason":"void","time":""}',
time: "",
command: "",
minetime: "24h",
lppan: "0",
tarta: "0",
botella: "0",
incubadora: "0",
lobo: "0",
loboegg: "0",
lobolife: "100",
elixirmagico: "0",
polvo: "0",
polvodesuerte: "0",
ojodearaña: "0",
lechuga: "0",
zanahoria: "0",
moneyspell: "0",

timega: "",
gaid: "",
ojo: "0",
lechuga: "0",
wmessage: "",

PREMIUMclassic: "false",
PREMIUMpro: "false",
PREMIUMgeneral: "false",
pdv: "false",
roleid: "",
mutedrole: "",
deletedIcon: "",
deletedMessage: "",
deletedAuthor: "",
deletedChannel: "",
ticketTitle: "",
user: "",
ticketchannel: "",
messageID: "",
ticketlimit: "",
categorything: "",
ticketC: "",
closed: "",
verified: "",
notverified: "",
Captcha: "",
newrole: "",
autorole: "",
incubadorap: "0",
bitcoin: "0",
discoduro: "0",  
motherboard: "0",
cpu: "0",
ps: "0",
gpu: "0",
Logs: "false",
botrole: "",
premiumbefore: "false",
antialtsms: "",
antialts: "false",
blockword1: "",
blockword2: "",
blockword3: "",
blockword4: "",
blockword5: "",
blockword6: "",
blockword7: "",
blockword8: "",
blockword9: "",
blockword10: "",
sysbw: "false",
confessauthor: "",
confesschannel: "",
wikischannel: "",
//blacklist
bl: "false",
bld:"",
blr: "",
blt: "",
//
pc: "0",
ram: "0",
pterodactyl: "0",
vsc: "0",
servidor: "0",
archivo: "0",
programa: "0",
antialt: "false",
days: "1",
cegg: "0",
conejo: "0",
//Insignias
DCM: "",
bughunter: "",
usuario: "",
premiumbadge: "",
devbadge: "",
workerbadge: "",
bugfixer: "",
pstatus: "",
profilepic: "",
dias: "",
betabadge: "",
pibadge: "",
sbl: ":x:",
//Invite Tracker
invitetracker: "off",
ivchannel: "",
invites: "0",
reales: "0",
falsas: "0",
//Logs
LogsChannel: "",
//Cajas
premiumbox: "0",
diamondbox: "0",
goldbox: "0",
//
reportsystem: "false",
reportchannel: "",
pause:"false",
//snipe
snipe:"empty|empty|null",
//RPG
himato: "0",
fhimato: "0",
botellademiel: "0",
twsubs: "0",
ElixirOscuro: "0",
cascominero: "0",
himatospell: "0",
profilecolor: "5869F2",
//Security
antiusers: "false",
antibots: "false", 
antichannels: "false",
antimalicious: "false",
// New RPG
ItemName: `{"type":"item","description":"descripción del item","etc":"..."}`,

//Supervivence
naturetoken: "0",
character: "",
supervivencetoken: "0",
defeatedbosses: "0",
characterlife: "10",
gamertoken : "0",
scoins: "0",
concreto: "0",
ladrillos: "0",
vendas: "0",
energy: "10",
mapa: "bosque",
roca: "0",
radio: "0",
sravioli: "0",
sagua: "0",
bunkernuclear: "0",
//TEst Vars
premiumcode1: "",
premiumcode2: "",
premiumcode3: "",
premiumcode4: "",
premiumcode5: "",
premiumcode6: "",
premiumcode7: "",
premiumcode8: "",
premiumcode9: "",
premiumcode10: "",
claim: "",

//Afk
afkt: "",
afkh: "",
afk: "",
//login
username: "",
password: "",
usernametaked: "",
usernametaked2: "",
account: "falso",
accountowner: "",
loggedin: "falso",
signoffcode: "",
//Premium
pstamp: "",
pleft: "",
//Welcome
wmessage: "",
wcolor: "BLACK",
wchannel: "",
wdescription: "",
wtitle: "Bienvenido!",
wactivated: "false",
//Premium Extra
pembedcolor: "#5865F2",
//idk
adminaffect: "yes",
afkr: "",
mail: "false",
//
newsimage: "",
newsmessage: "",
//AkenoOS
console_port: "1000",
console_open: "false",
console_lang: "en",

folder_1: "",
folder_2: "",
folder_3: "",
folder_name_1: "",
folder_name_2: "",
folder_name_3: "",
update_available: "true",
uptodate_version: "false",
update_version: "1.0.0",
directory: "C:/Akeno:",

};
module.exports = variables;